version: "3.9"
services:
  mssql-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD} 
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - "1433:1433"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  userapi:
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    container_name: userapi-container
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION_STRING}
      - ConnectionStrings__IncidentConnection=${INCIDENT_CONNECTION_STRING}
      - ConnectionStrings__RedisConnection=${REDIS_CONNECTION_STRING}
      - MSSQL_SERVER=${MSSQL_SERVER}
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_PASSWORD=${DB_PASSWORD}
      - USERAPI_DB=${USERAPI_DB}
      - INCIDENT_DB=${INCIDENT_DB}
    depends_on:
      - mssql-container
      - redis
    user: root  # Run as root user to avoid permission issues
    ports:
      - "8081:5000"

  webapp:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    container_name: webapp-container
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION_STRING}
      - ConnectionStrings__RedisConnection=${REDIS_CONNECTION_STRING}
      - USERAPI_BASEURL=${USERAPI_BASEURL}
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "8082:8080"
    depends_on:
      - userapi
      - redis

volumes:
  mssql-data:
