version: '3.8'

services:
  userapi:
    build:
      context: .  # The root of your project
      dockerfile: UserApi/Dockerfile  # Path to the Dockerfile for the UserApi service
    container_name: userapi-container
    ports:
      - "8081:5000"  # Map internal port 5000 to host's port 8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=UserApiDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - ConnectionStrings__IncidentConnection=Server=mssql;Database=IncidentDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - RedisConnection=redis  # Redis connection string
    networks:
      - backend

  webapp:
    build:
      context: .  # Root of your project
      dockerfile: WebApp/Dockerfile  # Path to the Dockerfile for WebApp
    container_name: webapp-container
    ports:
      - "8082:8080"  # Expose the WebApp web application on port 8082
    depends_on:
      - userapi
    networks:
      - backend

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
